// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMFLli5bWeH7iBr9QHmSWyc1ugQ_8lU-8',
    appId: '1:1008750887664:web:8e429885cd3c2d693d3835',
    messagingSenderId: '1008750887664',
    projectId: 'mp-gachi',
    authDomain: 'mp-gachi.firebaseapp.com',
    storageBucket: 'mp-gachi.appspot.com',
    measurementId: 'G-WDV1FWX05K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLwBPr00Zgsbz1RCNDk3rBI1emuasM8b0',
    appId: '1:1008750887664:android:95b1fbfef29ff04f3d3835',
    messagingSenderId: '1008750887664',
    projectId: 'mp-gachi',
    storageBucket: 'mp-gachi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARYcgO1EhLRDo8ji4_Ns3MYV_fvnTnaik',
    appId: '1:1008750887664:ios:9891f010551ada333d3835',
    messagingSenderId: '1008750887664',
    projectId: 'mp-gachi',
    storageBucket: 'mp-gachi.appspot.com',
    iosClientId: '1008750887664-nebi8f5brr905f4rvji0m7fn05menm8k.apps.googleusercontent.com',
    iosBundleId: 'com.example.gachi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARYcgO1EhLRDo8ji4_Ns3MYV_fvnTnaik',
    appId: '1:1008750887664:ios:9891f010551ada333d3835',
    messagingSenderId: '1008750887664',
    projectId: 'mp-gachi',
    storageBucket: 'mp-gachi.appspot.com',
    iosClientId: '1008750887664-nebi8f5brr905f4rvji0m7fn05menm8k.apps.googleusercontent.com',
    iosBundleId: 'com.example.gachi',
  );
}
