// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4TCa84P0blOJv2HnaUMEZDQvsltbha6A',
    appId: '1:878351682851:web:919f1c81fa4fe79cf79096',
    messagingSenderId: '878351682851',
    projectId: 'gachi-27bfd',
    authDomain: 'gachi-27bfd.firebaseapp.com',
    storageBucket: 'gachi-27bfd.appspot.com',
    measurementId: 'G-94Y9LQ95V3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXohqXq8mThmn_gUOfAttWKwPcurMpAo4',
    appId: '1:878351682851:android:bd09f5124d291d80f79096',
    messagingSenderId: '878351682851',
    projectId: 'gachi-27bfd',
    storageBucket: 'gachi-27bfd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf78WjYRkJH2P8eJ6qbW8KpRqo64Zv7W8',
    appId: '1:878351682851:ios:2ee605fde5fd5a3af79096',
    messagingSenderId: '878351682851',
    projectId: 'gachi-27bfd',
    storageBucket: 'gachi-27bfd.appspot.com',
    iosBundleId: 'com.example.gachi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf78WjYRkJH2P8eJ6qbW8KpRqo64Zv7W8',
    appId: '1:878351682851:ios:2ee605fde5fd5a3af79096',
    messagingSenderId: '878351682851',
    projectId: 'gachi-27bfd',
    storageBucket: 'gachi-27bfd.appspot.com',
    iosBundleId: 'com.example.gachi',
  );
}
